// Curated sample content for the knowledge_base table. This is a starter
// corpus — extend it freely (or swap in your own) and re-run `npm run seed`.
// content_type: 'roadmap_fragment' guides phase sequencing/topics.
// content_type: 'course' | 'resource' are candidate recommendations, always
// tagged is_free/price_usd so the RAG layer can label them correctly.

export interface SeedEntry {
  domain: string;
  content_type: "roadmap_fragment" | "resource" | "course";
  title: string;
  body: string;
  url?: string;
  provider?: string;
  is_free: boolean;
  price_usd?: number;
  skill_level?: "Beginner" | "Intermediate" | "Advanced";
  format?: "Video" | "Text/Docs" | "Project-based";
  tags?: string[];
}

const web: SeedEntry[] = [
  {
    domain: "Web Development",
    content_type: "roadmap_fragment",
    title: "Web dev foundations sequencing",
    body: "Beginners in web development should sequence learning as: semantic HTML and CSS layout (Flexbox, Grid) first, then core JavaScript (DOM, events, async/fetch) before touching any framework. Skipping straight to React without solid vanilla JS leads to shallow understanding of state and rendering. Budget 4-6 weeks for this stage at 6-8 hrs/week.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["html", "css", "javascript", "fundamentals"],
  },
  {
    domain: "Web Development",
    content_type: "roadmap_fragment",
    title: "Frontend framework and tooling stage",
    body: "Once fundamentals are solid, students should pick one frontend framework (React is the most in-demand for internships) and learn component architecture, hooks, and client-side routing. Pair this with Git/GitHub workflow and a build tool (Vite). Building 2-3 small projects (todo app, weather app, a CRUD app hitting a public API) cements the concepts better than tutorials alone.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["react", "git", "projects"],
  },
  {
    domain: "Web Development",
    content_type: "roadmap_fragment",
    title: "Full-stack and deployment stage",
    body: "Advanced stage: learn a backend runtime (Node.js/Express or Next.js API routes), a relational database (Postgres) with an ORM, authentication, and REST/GraphQL API design. Finish with deploying a full-stack project (Vercel/Render) and writing basic tests. This stage is what differentiates placement-ready candidates from tutorial-followers — a deployed, documented project matters more than course completion certificates.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["backend", "nodejs", "postgres", "deployment"],
  },
  {
    domain: "Web Development",
    content_type: "course",
    title: "The Odin Project — Full Stack JavaScript",
    body: "Free, project-heavy full-stack curriculum covering HTML/CSS, JavaScript, Node.js, React, and databases with real projects and a supportive community. Excellent for project-based learners who want depth over video-watching.",
    url: "https://www.theodinproject.com/",
    provider: "The Odin Project",
    is_free: true,
    skill_level: "Beginner",
    format: "Project-based",
    tags: ["fullstack", "javascript"],
  },
  {
    domain: "Web Development",
    content_type: "course",
    title: "freeCodeCamp Responsive Web Design",
    body: "Free certification covering HTML5 and CSS3 fundamentals through interactive coding challenges and 5 projects, ending with a portfolio-ready certificate.",
    url: "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
    provider: "freeCodeCamp",
    is_free: true,
    skill_level: "Beginner",
    format: "Project-based",
    tags: ["html", "css"],
  },
  {
    domain: "Web Development",
    content_type: "course",
    title: "JavaScript: The Hard Parts",
    body: "Video course going deep on closures, callbacks, the event loop, and async JavaScript — the concepts that trip up most self-taught developers moving into frameworks.",
    url: "https://frontendmasters.com/courses/javascript-hard-parts-v2/",
    provider: "Frontend Masters",
    is_free: false,
    price_usd: 39,
    skill_level: "Intermediate",
    format: "Video",
    tags: ["javascript", "async"],
  },
  {
    domain: "Web Development",
    content_type: "course",
    title: "React — The Complete Guide",
    body: "Comprehensive paid video course on React covering hooks, context, routing, and Redux with multiple guided projects — a common recommendation for structured video learners moving from fundamentals to frameworks.",
    url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
    provider: "Udemy",
    is_free: false,
    price_usd: 15,
    skill_level: "Intermediate",
    format: "Video",
    tags: ["react"],
  },
  {
    domain: "Web Development",
    content_type: "course",
    title: "Node.js, Express, MongoDB & More",
    body: "Paid video course building a full backend API from scratch with Express and a NoSQL database, including authentication and deployment — pairs well after finishing a frontend framework course.",
    url: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
    provider: "Udemy",
    is_free: false,
    price_usd: 15,
    skill_level: "Advanced",
    format: "Video",
    tags: ["backend", "nodejs"],
  },
  {
    domain: "Web Development",
    content_type: "resource",
    title: "MDN Web Docs",
    body: "The canonical free reference documentation for HTML, CSS and JavaScript, maintained by Mozilla — best used alongside any course as the source of truth for syntax and browser behavior.",
    url: "https://developer.mozilla.org/",
    provider: "Mozilla",
    is_free: true,
    skill_level: "Beginner",
    format: "Text/Docs",
    tags: ["reference", "docs"],
  },
];

const ml: SeedEntry[] = [
  {
    domain: "Machine Learning",
    content_type: "roadmap_fragment",
    title: "ML math and Python foundations",
    body: "Before any ML library, students need working Python (NumPy, pandas, Matplotlib) and enough linear algebra, probability, and calculus intuition to understand gradients and distributions — not a full math degree, but enough to read model documentation. 4-5 weeks at 6+ hrs/week is realistic for someone starting from basic Python.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["python", "math", "numpy"],
  },
  {
    domain: "Machine Learning",
    content_type: "roadmap_fragment",
    title: "Classical ML and scikit-learn stage",
    body: "Next, learn classical ML: regression, classification, decision trees, ensembles, and evaluation metrics using scikit-learn. Complete at least 2 Kaggle-style tabular datasets end-to-end (EDA, feature engineering, model comparison) rather than just watching lectures — this stage is where most learning-by-doing should happen.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["scikit-learn", "kaggle"],
  },
  {
    domain: "Machine Learning",
    content_type: "roadmap_fragment",
    title: "Deep learning and specialization stage",
    body: "Advanced stage: pick a framework (PyTorch is more common in research and most placement interviews) and learn neural networks, CNNs for vision or transformers for NLP depending on interest. Build one substantial project with a written report — this is the artifact to show in interviews and a strong resume differentiator for ML-focused placements or higher studies applications.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["pytorch", "deep-learning"],
  },
  {
    domain: "Machine Learning",
    content_type: "course",
    title: "Kaggle Learn — Python & Intro to ML",
    body: "Free, bite-sized hands-on micro-courses directly in the browser, covering Python basics through intermediate machine learning with immediate practice exercises.",
    url: "https://www.kaggle.com/learn",
    provider: "Kaggle",
    is_free: true,
    skill_level: "Beginner",
    format: "Project-based",
    tags: ["python", "ml-basics"],
  },
  {
    domain: "Machine Learning",
    content_type: "course",
    title: "Machine Learning Specialization",
    body: "Andrew Ng's widely-recommended video specialization covering supervised/unsupervised learning and best practices, free to audit or paid for a certificate — a strong structured entry point for video learners.",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    provider: "Coursera / DeepLearning.AI",
    is_free: false,
    price_usd: 49,
    skill_level: "Beginner",
    format: "Video",
    tags: ["andrew-ng", "fundamentals"],
  },
  {
    domain: "Machine Learning",
    content_type: "course",
    title: "Practical Deep Learning for Coders",
    body: "Free, project-first deep learning course from fast.ai that gets students training real models (vision, NLP, tabular) from lesson one, with theory introduced as needed rather than upfront.",
    url: "https://course.fast.ai/",
    provider: "fast.ai",
    is_free: true,
    skill_level: "Advanced",
    format: "Project-based",
    tags: ["deep-learning", "pytorch"],
  },
  {
    domain: "Machine Learning",
    content_type: "course",
    title: "Deep Learning Specialization",
    body: "Paid, in-depth video specialization covering neural networks, CNNs, sequence models and transformers, widely referenced in ML interview prep for placements and grad-school applications.",
    url: "https://www.coursera.org/specializations/deep-learning",
    provider: "Coursera / DeepLearning.AI",
    is_free: false,
    price_usd: 49,
    skill_level: "Advanced",
    format: "Video",
    tags: ["deep-learning", "neural-networks"],
  },
  {
    domain: "Machine Learning",
    content_type: "resource",
    title: "scikit-learn User Guide",
    body: "Free official documentation with worked examples for every classical ML algorithm in the library — the reference to keep open while working through Kaggle datasets.",
    url: "https://scikit-learn.org/stable/user_guide.html",
    provider: "scikit-learn",
    is_free: true,
    skill_level: "Intermediate",
    format: "Text/Docs",
    tags: ["reference", "docs"],
  },
];

const dsa: SeedEntry[] = [
  {
    domain: "DSA & Competitive Programming",
    content_type: "roadmap_fragment",
    title: "Core data structures stage",
    body: "Start with arrays, strings, linked lists, stacks, and queues, implementing each from scratch once before relying on library implementations. Solve 8-10 easy problems per structure on a judge (LeetCode/GfG) before moving on — recognition of patterns matters more than raw problem count at this stage.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["arrays", "linked-list"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "roadmap_fragment",
    title: "Trees, graphs and recursion stage",
    body: "Move to recursion/backtracking, trees (BST, traversals), heaps, and graph algorithms (BFS/DFS, shortest paths). This is typically the longest and hardest stage for students preparing for placements — plan 6-8 weeks with daily practice rather than cramming, and revisit graph problems weekly since they decay fastest from memory.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["trees", "graphs", "recursion"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "roadmap_fragment",
    title: "Dynamic programming and interview readiness stage",
    body: "Advanced stage: dynamic programming (1D/2D, knapsack patterns), greedy algorithms, and mock interviews under time pressure. For placement or hackathon goals, timed contests (Codeforces/LeetCode contests) build the speed that untimed practice doesn't. Aim for consistent participation over the final 4-6 weeks before interview season.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["dp", "interview-prep"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "course",
    title: "NeetCode 150",
    body: "Free curated list of 150 high-yield interview problems organized by pattern, with free video explanations for each — the most commonly recommended structured problem set for placement prep.",
    url: "https://neetcode.io/practice",
    provider: "NeetCode",
    is_free: true,
    skill_level: "Intermediate",
    format: "Video",
    tags: ["leetcode", "patterns"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "course",
    title: "Striver's A2Z DSA Course",
    body: "Free, extremely thorough sheet-plus-video course covering every DSA topic from basics to advanced graphs/DP with structured problem sequencing — popular among Indian college students preparing for placements.",
    url: "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/",
    provider: "takeUforward",
    is_free: true,
    skill_level: "Beginner",
    format: "Video",
    tags: ["dsa", "placement-prep"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "course",
    title: "Grokking the Coding Interview",
    body: "Paid, pattern-based interview prep course teaching reusable problem-solving templates (sliding window, two pointers, etc.) rather than memorizing individual solutions.",
    url: "https://www.designgurus.io/course/grokking-the-coding-interview",
    provider: "DesignGurus",
    is_free: false,
    price_usd: 79,
    skill_level: "Advanced",
    format: "Text/Docs",
    tags: ["patterns", "interview-prep"],
  },
  {
    domain: "DSA & Competitive Programming",
    content_type: "resource",
    title: "Codeforces",
    body: "Free competitive programming judge with regular timed contests and an editorial for nearly every problem — the standard venue for building contest speed once fundamentals are solid.",
    url: "https://codeforces.com/",
    provider: "Codeforces",
    is_free: true,
    skill_level: "Advanced",
    format: "Project-based",
    tags: ["contests", "practice"],
  },
];

const app: SeedEntry[] = [
  {
    domain: "App Development",
    content_type: "roadmap_fragment",
    title: "Mobile fundamentals and framework choice",
    body: "Students should first decide native vs cross-platform: React Native or Flutter for one codebase across iOS/Android (recommended for most students due to faster shipping and larger job demand), or Kotlin/Swift for native-only roles. Learn the chosen language basics and the framework's component/widget model before building UI.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["react-native", "flutter"],
  },
  {
    domain: "App Development",
    content_type: "roadmap_fragment",
    title: "State, navigation and device APIs stage",
    body: "Next, learn navigation/routing, state management (Provider/Riverpod for Flutter, Context/Zustand for React Native), and integrating device APIs (camera, location, storage). Build a multi-screen app with real API data — a notes app or a weather app with local storage — to practice these together.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["state-management", "apis"],
  },
  {
    domain: "App Development",
    content_type: "roadmap_fragment",
    title: "Backend integration and publishing stage",
    body: "Advanced stage: connect the app to a real backend (Firebase or a custom REST API), add authentication and push notifications, then package and publish a build (even an internal test track). A published, backend-connected app is a much stronger portfolio piece than a purely local UI project for both internships and hackathons.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["firebase", "publishing"],
  },
  {
    domain: "App Development",
    content_type: "course",
    title: "Flutter & Dart — The Complete Guide",
    body: "Popular paid video course covering Dart fundamentals through building and publishing multiple Flutter apps, including state management and Firebase integration.",
    url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
    provider: "Udemy",
    is_free: false,
    price_usd: 15,
    skill_level: "Beginner",
    format: "Video",
    tags: ["flutter", "dart"],
  },
  {
    domain: "App Development",
    content_type: "course",
    title: "React Native official documentation tutorial",
    body: "Free official walkthrough covering core components, navigation, and platform APIs directly from the framework maintainers — a solid free-first alternative to a paid video course.",
    url: "https://reactnative.dev/docs/tutorial",
    provider: "React Native",
    is_free: true,
    skill_level: "Beginner",
    format: "Text/Docs",
    tags: ["react-native"],
  },
  {
    domain: "App Development",
    content_type: "course",
    title: "Flutter Foundations",
    body: "Free official Flutter documentation course covering the widget tree, layout, navigation, and state management in depth, maintained by the Flutter team.",
    url: "https://docs.flutter.dev/foundation",
    provider: "Flutter",
    is_free: true,
    skill_level: "Intermediate",
    format: "Text/Docs",
    tags: ["flutter"],
  },
  {
    domain: "App Development",
    content_type: "course",
    title: "The Complete Firebase & Flutter Bootcamp",
    body: "Paid project-based course building a full app with Firebase authentication, Firestore, and cloud functions — matches the backend-integration stage well.",
    url: "https://www.udemy.com/course/flutter-firebase-bootcamp/",
    provider: "Udemy",
    is_free: false,
    price_usd: 15,
    skill_level: "Advanced",
    format: "Project-based",
    tags: ["firebase", "flutter"],
  },
];

const cloud: SeedEntry[] = [
  {
    domain: "Cloud & DevOps",
    content_type: "roadmap_fragment",
    title: "Linux, networking and Git foundations",
    body: "Before any cloud provider, students should be comfortable with the Linux command line, basic networking concepts (DNS, HTTP, ports), and Git workflows. This foundation makes every later cloud/DevOps tool far easier to reason about instead of memorizing disconnected commands.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["linux", "networking"],
  },
  {
    domain: "Cloud & DevOps",
    content_type: "roadmap_fragment",
    title: "Cloud provider and containers stage",
    body: "Learn one cloud provider in depth (AWS is the most requested in internships) covering compute, storage, and IAM basics, alongside Docker for containerization. Deploy a small app end-to-end (containerize it, push to a registry, run it on a managed service) rather than only studying certification material.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["aws", "docker"],
  },
  {
    domain: "Cloud & DevOps",
    content_type: "roadmap_fragment",
    title: "CI/CD and orchestration stage",
    body: "Advanced stage: set up CI/CD pipelines (GitHub Actions), learn infrastructure-as-code basics (Terraform), and get an introduction to Kubernetes for orchestration. A documented pipeline that auto-deploys a personal project is a strong, verifiable portfolio piece for DevOps-focused internship applications.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["ci-cd", "kubernetes", "terraform"],
  },
  {
    domain: "Cloud & DevOps",
    content_type: "course",
    title: "AWS Cloud Practitioner Essentials",
    body: "Free official AWS training covering core cloud concepts and services, designed as prep for the entry-level Cloud Practitioner certification.",
    url: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/",
    provider: "AWS Training",
    is_free: true,
    skill_level: "Beginner",
    format: "Video",
    tags: ["aws", "certification"],
  },
  {
    domain: "Cloud & DevOps",
    content_type: "course",
    title: "Docker & Kubernetes: The Complete Guide",
    body: "Popular paid video course taking students from Docker basics through deploying multi-container apps on Kubernetes, with hands-on projects throughout.",
    url: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    provider: "Udemy",
    is_free: false,
    price_usd: 15,
    skill_level: "Intermediate",
    format: "Video",
    tags: ["docker", "kubernetes"],
  },
  {
    domain: "Cloud & DevOps",
    content_type: "course",
    title: "GitHub Actions documentation",
    body: "Free official documentation and guided quickstarts for building CI/CD pipelines directly in GitHub — enough to set up automatic testing and deployment for a personal project.",
    url: "https://docs.github.com/en/actions",
    provider: "GitHub",
    is_free: true,
    skill_level: "Advanced",
    format: "Text/Docs",
    tags: ["ci-cd"],
  },
];

const security: SeedEntry[] = [
  {
    domain: "Cybersecurity",
    content_type: "roadmap_fragment",
    title: "Security and networking fundamentals",
    body: "Start with computer networking basics (OSI model, TCP/IP, common protocols) and operating system fundamentals for both Linux and Windows, since almost every later security topic assumes this. Pair theory with a home lab (a VM running Kali Linux) to practice hands-on rather than only reading.",
    is_free: true,
    skill_level: "Beginner",
    tags: ["networking", "linux"],
  },
  {
    domain: "Cybersecurity",
    content_type: "roadmap_fragment",
    title: "Web security and practical hacking stage",
    body: "Next, learn the OWASP Top 10 web vulnerabilities and practice on legal training platforms (TryHackMe, PortSwigger Web Security Academy). This is the stage where structured, guided labs matter most since real-world targets aren't legal to practice on without authorization.",
    is_free: true,
    skill_level: "Intermediate",
    tags: ["owasp", "web-security"],
  },
  {
    domain: "Cybersecurity",
    content_type: "roadmap_fragment",
    title: "CTFs and specialization stage",
    body: "Advanced stage: participate in Capture The Flag competitions to build applied skills under time pressure, and pick a specialization (penetration testing, cloud security, or malware analysis) to go deeper in. A documented CTF writeup portfolio is often more convincing to recruiters than certificates alone.",
    is_free: true,
    skill_level: "Advanced",
    tags: ["ctf", "specialization"],
  },
  {
    domain: "Cybersecurity",
    content_type: "course",
    title: "TryHackMe — Pre Security & Intro to Cyber Security paths",
    body: "Free (with an optional paid subscription for advanced rooms) guided, gamified learning paths covering networking, Linux, and web security fundamentals with hands-on virtual machines.",
    url: "https://tryhackme.com/",
    provider: "TryHackMe",
    is_free: true,
    skill_level: "Beginner",
    format: "Project-based",
    tags: ["hands-on", "networking"],
  },
  {
    domain: "Cybersecurity",
    content_type: "course",
    title: "PortSwigger Web Security Academy",
    body: "Free, extremely well-regarded set of labs covering web vulnerabilities (SQLi, XSS, SSRF, etc.) built by the makers of Burp Suite, widely used as the standard for practical web security training.",
    url: "https://portswigger.net/web-security",
    provider: "PortSwigger",
    is_free: true,
    skill_level: "Intermediate",
    format: "Project-based",
    tags: ["web-security", "owasp"],
  },
  {
    domain: "Cybersecurity",
    content_type: "course",
    title: "Practical Ethical Hacking",
    body: "Paid, highly-rated video course covering penetration testing methodology end-to-end, from networking basics through Active Directory attacks and report writing.",
    url: "https://academy.tcm-sec.com/p/practical-ethical-hacking-the-complete-course",
    provider: "TCM Security Academy",
    is_free: false,
    price_usd: 30,
    skill_level: "Advanced",
    format: "Video",
    tags: ["pentesting"],
  },
];

export const SEED_ENTRIES: SeedEntry[] = [
  ...web,
  ...ml,
  ...dsa,
  ...app,
  ...cloud,
  ...security,
];
